version: '3.8'
services:
  mssql-container-image:
    image: tamilcodingwizard/productsdb:v1.0
    environment:
      MSSQL_SA_PASSWORD: Admin1234!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - ecommerce_nw
    hostname: sqlserver
    container_name: sqlserver

  products-api-image:
    image: tamilcodingwizard/ecommerce-products:v2.0
    environment:
      MSSQL_Pwd: Admin1234!
      MSSQL_Server: sqlserver
    networks:
      - ecommerce_nw
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: on-failure

  postgres-container:
    image: postgres:16.1
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=Admin
      - POSTGRES_DB=Users
    ports:
      - "5432:5432"
    networks:
      - ecommerce_nw
    volumes:
      - ./DC/postgres-init:/docker-entrypoint-initdb.d
    
  users-api-image:
    image: tamilcodingwizard/ecommerce-users:v1.0
    ports:
      - "9090:9090"
    environment:
      - HOST_NAME=postgres-container
      - HOST_PASSWORD=1234
    networks:
      - ecommerce_nw

networks:
  ecommerce_nw:
    driver: bridge

