version: '3.8'
services:
 msssql-image:
   image: tamilcodingwizard/productsdb:v1.0
   environment:
      MSSQL_SA_PASSWORD: Admin1234!
      ACCEPT_EULA: Y
   ports:
      - "1433:1433"
   networks:
      - products_nw
   hostname: sqlserver
   container_name: sqlserver
 products-api-image:
   image: tamilcodingwizard/ecommerce-products:v2.0
   environment:
     MSSQL_Pwd: Admin1234!
     MSSQL_Server: sqlserver
   networks:
      - products_nw
   ports:
      - "8080:8080"
      - "8081:8081"
networks:
 products_nw:
  driver: bridge
 